### ISSUE TITLE
你好，我对 mybatis 的 golang 的实现很感兴趣，但我发现 light 有下列几个问题，请问你有什么解决方案

### ISSUE THREAD

**Issue by runner-mei** [arstd/light#4]
你好，我对 mybatis 的 golang 的实现很感兴趣，但我发现 light 有下列几个问题，请问你有什么解决方案
1. 多数据库的支持
2. 根据方法中参数生成不条件查询的支持，就是 mybatis 中 if...else...的支持

如果有想法的话，我愿意参与开发

**Comment by runner-mei** [comment]
我先看一遍你的源代码，再来和你讨论

**Comment by arstd** [comment]
源码有点乱，我打算重写了，你加我微信吧 shangxuejin

**Comment by runner-mei** [comment]
搜不到啊

**Comment by arstd** [comment]
。。。添加好友，搜索，就能找到了啊，我加你，或者发邮件给我？

**Comment by runner-mei** [comment]
qq 行么 409248665
weixin: 13311601608

**Comment by arstd** [comment]
加你微信了
