### ISSUE TITLE
Do you support transaction, transaction manager?

### ISSUE THREAD

**Issue by zhuxiujia** [arstd/light#7]
it support transaction, transaction manager? like SpringMVC?

**Comment by zhuxiujia** [comment]
and it support  xml file? like mybatis?

**Comment by arstd** [comment]
You can pass `tx` to the method, but you must begin tx manually.

https://github.com/arstd/light/blob/master/example/store/user_test.go#L44

**Comment by arstd** [comment]
Comment with `[...]` and `?` is so simple and convenient as to forget xml file.

**Comment by zhuxiujia** [comment]
看起来是挺方便的，但是如果你的开发团队是企业的规模的话，让不懂go的DBA来改代码确实太麻烦，感觉还是mybatis这种代码和sql分离的这种可读性，维护性高一点。

**Comment by arstd** [comment]
DBA 深入到代码逻辑，这种情况还是比较少见的，除非对业务非常熟悉。一般来说，SQL是代码的一部分，改 SQL 不改代码，可能会造成不可预知的风险。

如果确实有这种需求，建议尝试其他库，例如 https://github.com/yinshuwei/osm，这个库也开发了好几年了，还在不断升级维护。
