### ISSUE TITLE
对 light 的改进建议

### ISSUE THREAD

**Issue by mei-rune** [arstd/light#9]
你好，我是 GoBatis 的作者，之前因为和你交流过，因为想法不一致，我创建了 GoBatis, GoBatis 在我公司用的挺好，但仍有不足，觉得 light 是一个很好的补充。

我有时会开发一些项目，这项目只有 30 条以下的 SQL，如果用 GoBatis 就显示太大了，不合算。
但又很喜欢 从接口生成实现 的开发方式。用 light 就很合适。但有下列两个要求
   1. 生成的代码不会产生新依赖， 因为我不愿意为了不多的代码引入新依赖， 现在有 light 会引入 "github.com/arstd/light/light" 和  “github.com/arstd/light/null"， 我认为可以去掉
   2. 多数据库的支持( 可选 ， 这个有必要，但不是必须)

**Comment by arstd** [comment]
感谢关注这个项目，先对你提的两个要求，解释一下：
1. 依赖问题，我注意到了，本身并不想依赖任何东西，但是有些功能实现不了，或者说很麻烦，不得已，才引入的；
2. 多数据库一直想做的。

但是最近一年都特别忙，代码逐渐写得少了，也没有新的思路。
不知道使用这个项目的人多不多，所以也没有话太多时间精力，主要是自己用到了才做的。

随着 Go 版本更新和 SQL 驱动的更新，有很多功能可能不在需要依赖外部了，有时间，我会继续重构这个项目。

我的目标就是实现一套 SpringMVC＋MyBatis 的框架，但是使用地道的 Go （我个人觉得 xml 方式并不是地道的 Go ），同时提供代码生成和反射两种使用方式。
目前 light 是基本实现了 MyBatis 功能（代码生成方式），内部项目也实现了 SpringMVC 类似的功能（反射方式）。
可能还要研究一下 Go2.0 新特性，看看有没有创新点吧。

**Comment by mei-rune** [comment]
你最近都不维护了， 挺好的东西啊， 继续维护啊

**Comment by omigo** [comment]
感觉路子有点偏了，我发现 sqlx 已经很好了，我现在就用这它，手写点代码也没觉得有多大工作量。

大多数人还是习惯使用 lib，而不是生成代码。而且生成代码代复杂了，一个类型就要很多代码去处理，还有各种方言，全支持，有难度。

还有一个问题，就是生成代码的性能，如果大项目，解析源码，要解析到字段，可能需要很长时间。总之稳定性难以保障，复杂性超过了它本身带来的好处。

所以，我觉得，可以针对常用功能做一个小的代码生成器，不做过多扩展。
如果想继续研究，可以参考一下 sqlc 这个项目。

另外，AI 时代已经来了，我认为，代码生成 Copilot 或其他智能工具  将来可能会很好地完成这类工作，使用起来更顺手。所以我个人认为没必要再走老路了。

**Comment by mei-rune** [comment]
sqlx 也挺好， 在我一个人的项目时也用它， 但是多个人时就不好了， 重构时更加头大

你可以试试我的 GoBatis,   单单是 GoBatis 还体现在出来好处， 我还有一个 gogen ，  是一个生成 web 服务代码的工具， 这两个加起来就爽了。
